[package]
name = "xzam"
version = "0.1.0"
edition = "2024"

[dependencies]
hound = "3.5.1"
thiserror = "2.0.12"
rustfft = "6.3.0"
rayon = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v4"] }